// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bytveyhsiunlxuxbttxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dHZleWhzaXVubHh1eGJ0dHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEyMTAsImV4cCI6MjA2NTQ2NzIxMH0.wR4OPVYa7a6huHaGBdy1bb8C8mzt-Hda5jiccipeYPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);